# Generated by Django 3.1.7 on 2021-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='abc', max_length=32)),
                ('password', models.CharField(default='abc', max_length=128)),
            ],
        ),
    ]
