# Generated by Django 3.1.7 on 2021-04-12 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False)),
                ('tip', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('free_kids_meal', models.IntegerField(default=0)),
                ('delivered', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('table_num', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField(default=1)),
                ('order_id', models.CharField(default='abc', max_length=50)),
                ('status', models.CharField(default='ss', max_length=50)),
                ('tax', models.DecimalField(decimal_places=2, default=8.25, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableNum', models.IntegerField(null=True)),
                ('occupied', models.BooleanField(default=False)),
                ('order_status', models.CharField(blank=True, default='browsing', max_length=12, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('waiter_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('unresolved', models.BooleanField(default=True)),
                ('drink', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.item')),
                ('orderx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='orderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=3, default=10.0, max_digits=7)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('order_id', models.CharField(default='abc', max_length=50)),
                ('Item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.item')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='orders.orderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('unresolved', models.BooleanField(default=True)),
                ('orderx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
