# Generated by Django 3.1.7 on 2021-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0004_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField(default=0, max_length=3)),
                ('time', models.DateTimeField()),
                ('total_items', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Created', 'created'), ('In progress', 'in progress'), ('Finished', 'finished'), ('Delivered', 'delivered')], max_length=50)),
                ('order_id', models.IntegerField(max_length=10, null=True)),
                ('Item', models.ManyToManyField(to='menu.Item')),
            ],
        ),
    ]
