# Generated by Django 3.1.7 on 2021-04-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='free_dessert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='free_dessert_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='order',
            name='free_dessert_hold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='free_dessert_tries',
            field=models.IntegerField(default=0),
        ),
    ]
