# Generated by Django 3.1.7 on 2021-03-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_item_image'),
        ('orders', '0004_auto_20210327_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.item'),
        ),
    ]
