# Generated by Django 3.1.7 on 2021-03-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20210328_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_item',
            new_name='items',
        ),
    ]
